spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/microservice?createDatabaseIfNotExist=true
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defeaultZone: http://localhost:8761/eureka
